=== JondaHealthTech/intersystem/IRISHealth/dev/studio/templates/htmltags.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by Marvin Tener (private) -->
<!--DTD generated by XMLSPY v2004 rel. 2 U (http://www.xmlspy.com)-->
<!ELEMENT attr EMPTY>
<!ATTLIST attr
	name (P1 | P2 | P3 | P4 | XMLNS:SQL | XMLNS:XSQL | abbr | accept | accept-charset | accesskey | action | align | alink | alt | archive | arg1 | arg2 | arg3 | arg4 | axis | background | bgcolor | block | border | caption | cellpadding | cellspacing | char | charoff | charset | checked | cite | class | classid | classname | clear | code | codebase | codetype | color | cols | colspan | condition | connection | content | coords | counter | cspbind | cspnotrim | csprequired | cspcaption | cspvalid | cspevent | cspjs | cursor | data | datasource | datetime | declare | defaulttext | defer | delimiter | description | dir | disabled | domain | encoded | enctype | errorpage | expires | face | features | field | form | frame | frameborder | from | headers | height | href | hreflang | hspace | http-equiv | id | idname | import | includes | into | ismap | label | lang | language | link | longdesc | marginheight | marginwidth | max-rows | maxlength | maxrows | media | method | mode | multiple | name | new | nocharsetconvert | nohref | noresize | noshade | nowrap | object | objid | objidattr | onblur | onchange | onclick | ondblclick | onfocus | onkeydown | onkeypress | onkeyup | onload | onmousedown | onmousemove | onmouseout | onmouseover | onmouseup | onreset | onselect | onsubmit | onunload | options | order | page | password | predicates | private | query | queryname | readonly | rel | rev | row-element | rows | rowset-element | rowspan | rules | runat | scheme | scope | scrolling | select | selected | shape | showsql | size | skip-rows | src | standby | start | startvalues | step | style | summary | super | tabindex | tag-case | target | text | textid | title | to | type | usemap | username | valign | value | valuetype | vars | vlink | vspace | where | width) #REQUIRED
	type (boolean | char | color | datetime | enum | number | script | string | uri) #REQUIRED
	enum CDATA #IMPLIED
	desc CDATA #REQUIRED
	cat (CSPBind | Cache | Core | CSPText | Event | JavaScript | Lang | Other | SQL) #IMPLIED
	enumlist CDATA #IMPLIED
>
<!ELEMENT attrs (#PCDATA | attr)*>
<!ELEMENT description (#PCDATA)>
<!ELEMENT element (description?, attrs?)>
<!ATTLIST element
	ename (A | ADDRESS | APPLET | AREA | B | BASEFONT | BDO | BLOCKQUOTE | BODY | BR | CAPTION | CENTER | CSP:CLASS | CSP:COMMENT | CSP:CONTENT | CSP:CONTINUE | CSP:ELSE | CSP:ELSEIF | CSP:IF | CSP:INCLUDE | CSP:LOOP | CSP:NEW | CSP:OBJECT | CSP:QUERY | CSP:QUIT | CSP:SEARCH | CSP:SECTION | CSP:SQLQUERY | CSP:StudioGenerateTemplate | CSP:StudioInteractiveTemplate | CSP:StudioSimpleTemplate | CSP:TEXT | CSP:WHILE | DEL | DIV | EM | FONT | FORM | FRAME | FRAMESET | H1 | H2 | H3 | H4 | H5 | H6 | HEAD | HR | HTML | I | IFRAME | IMG | INPUT | INS | LI | LINK | MAP | META | NOBR | NOFRAMES | OBJECT | OL | OPTGROUP | OPTION | P | PARAM | PRE | Q | SCRIPT | SELECT | SPAN | SQL:QUERY | STRONG | SUB | SUP | TABLE | TD | TEXTAREA | TH | TITLE | TR | UL | XSQL:QUERY) #REQUIRED
	edesc CDATA #REQUIRED
	empty CDATA #IMPLIED
>
<!ELEMENT elementlist (element+)>
	<!ENTITY coreattrs "
<attr name=&#34;id&#34;     cat=&#34;Core&#34; type=&#34;string&#34; desc=&#34;Unique identifier.&#34; />
<attr name=&#34;class&#34;  cat=&#34;Core&#34; type=&#34;string&#34; desc=&#34;Space-separated list of classes.&#34; />
<attr name=&#34;style&#34;  cat=&#34;Core&#34; type=&#34;string&#34; desc=&#34;Associated style info.&#34; />
<attr name=&#34;title&#34;  cat=&#34;Core&#34; type=&#34;string&#34; desc=&#34;Advisory title.&#34; />

">
	<!ENTITY i18n "

<attr name=&#34;lang&#34;  cat=&#34;Lang&#34; type=&#34;string&#34; desc=&#34;Language code.&#34; />
<attr name=&#34;dir&#34;  cat=&#34;Lang&#34; type=&#34;enum&#34; enum=&#34;ltr|rtl&#34; desc=&#34;Direction for weak/neutral text.&#34; />

">
	<!ENTITY events "
<attr name=&#34;onclick&#34;     cat=&#34;Event&#34; type=&#34;script&#34; desc=&#34;A pointer button was clicked.&#34; />
<attr name=&#34;ondblclick&#34;  cat=&#34;Event&#34; type=&#34;script&#34; desc=&#34;A pointer button was double clicked.&#34; />
<attr name=&#34;onmousedown&#34; cat=&#34;Event&#34; type=&#34;script&#34; desc=&#34;A pointer button was pressed down.&#34; />
<attr name=&#34;onmouseup&#34;   cat=&#34;Event&#34; type=&#34;script&#34; desc=&#34;A pointer button was released.&#34; />
<attr name=&#34;onmouseover&#34; cat=&#34;Event&#34; type=&#34;script&#34; desc=&#34;A pointer was moved onto.&#34; />
<attr name=&#34;onmousemove&#34; cat=&#34;Event&#34; type=&#34;script&#34; desc=&#34;A pointer was moved within.&#34; />
<attr name=&#34;onmouseout&#34;  cat=&#34;Event&#34; type=&#34;script&#34; desc=&#34;A pointer was moved away.&#34; />
<attr name=&#34;onkeypress&#34;  cat=&#34;Event&#34; type=&#34;script&#34; desc=&#34;A key was pressed and released.&#34; />
<attr name=&#34;onkeydown&#34;   cat=&#34;Event&#34; type=&#34;script&#34; desc=&#34;A key was pressed down.&#34; />
<attr name=&#34;onkeyup&#34;     cat=&#34;Event&#34; type=&#34;script&#34; desc=&#34;A key was released.&#34; />
">
	<!ENTITY attrs "&coreattrs; &i18n; &events;">
	<!ENTITY align "left|center|right|justify">
	<!ENTITY csptext "
<attr name=&#34;textid&#34;    cat=&#34;CSPText&#34;   type=&#34;string&#34; desc=&#34;The text string identifier within the domain.&#34; />
<attr name=&#34;domain&#34;    cat=&#34;CSPText&#34;   type=&#34;string&#34; desc=&#34;The optional application domain for looking up this text.  &#37;response.Domain is used if not specified.&#34; />
<attr name=&#34;language&#34;  cat=&#34;CSPText&#34;   type=&#34;string&#34; desc=&#34;The optional RFC 1766 format language name for looking up this text. &#37;response.Language is used if not specified.&#34; />
<attr name=&#34;arg1&#34;      cat=&#34;CSPText&#34;   type=&#34;string&#34; desc=&#34;Replaces &#37;1 in the message text.&#34; />
<attr name=&#34;arg2&#34;      cat=&#34;CSPText&#34;   type=&#34;string&#34; desc=&#34;Replaces &#37;2 in the message text.&#34; />
<attr name=&#34;arg3&#34;      cat=&#34;CSPText&#34;   type=&#34;string&#34; desc=&#34;Replaces &#37;3 in the message text.&#34; />
<attr name=&#34;arg4&#34;      cat=&#34;CSPText&#34;   type=&#34;string&#34; desc=&#34;Replaces &#37;4 in the message text.&#34; />
">
	<!ENTITY cspbind "
<attr name=&#34;cspbind&#34;     cat=&#34;CSPBind&#34;   type=&#34;string&#34; desc=&#34;The name of the object property to be bound.&#34; />
<attr name=&#34;cspnotrim&#34;   cat=&#34;CSPBind&#34;   type=&#34;boolean&#34; desc=&#34;If present, do not blank trim object values.&#34; />
<attr name=&#34;csprequired&#34; cat=&#34;CSPBind&#34;   type=&#34;boolean&#34; desc=&#34;If present, indicates that a value must be supplied.&#34; />
<attr name=&#34;cspvalid&#34;    cat=&#34;CSPBind&#34;   type=&#34;string&#34; desc=&#34;Client-side JavaScript code to run to validate the element&#39;s contents.&#34; />
<attr name=&#34;cspcaption&#34;  cat=&#34;CSPBind&#34;   type=&#34;string&#34; desc=&#34;Name to use for property in error messages.&#34; />
<attr name=&#34;delimiter&#34;   cat=&#34;CSPBind&#34;   type=&#34;string&#34; desc=&#34;Delimiter to use between elements of a list.&#34; />
">

=== JondaHealthTech/intersystem/IRISHealth/dev/studio/templates/htmltags.xml
<?xml version="1.0"?>
<!-- List of HTML elements/attributes used by HTML Tag Inspector -->
<!-- Copyright (c) 2001, InterSystems Corp. ALL RIGHTS RESERVED -->
<!DOCTYPE elementlist SYSTEM "htmltags.dtd">
<elementlist>
	<!-- FORMATTING TAGS -->
	<!-- SPAN TAG -->
	<element ename="SPAN" edesc="SPAN Tag">
		<attrs>
&attrs;
&csptext;
</attrs>
	</element>
	<!-- SUP TAG -->
	<element ename="SUP" edesc="Superscript Tag">
		<attrs>
&attrs;
</attrs>
	</element>
	<!-- SUB TAG -->
	<element ename="SUB" edesc="Subscript Tag">
		<attrs>
&attrs;
</attrs>
	</element>
	<!-- BDO TAG -->
	<element ename="BDO" edesc="Overrides bidirectional algorithms for content display">
		<attrs>
&attrs;
<attr name="dir" type="enum" enum="rtl|ltr" desc="Text direction."/>
			<attr name="lang" type="string" desc="Language."/>
		</attrs>
	</element>
	<!-- B TAG -->
	<element ename="B" edesc="Boldface Tag">
		<attrs>
&attrs;
</attrs>
	</element>
	<!-- I TAG -->
	<element ename="I" edesc="Italics Tag">
		<attrs>
&attrs;
</attrs>
	</element>
	<!-- STRONG TAG -->
	<element ename="STRONG" edesc="Strong Tag">
		<attrs>
&attrs;
</attrs>
	</element>
	<!-- EM TAG -->
	<element ename="EM" edesc="Emphasis Tag">
		<attrs>
&attrs;
</attrs>
	</element>
	<!-- BASEFONT TAG -->
	<element ename="BASEFONT" edesc="base font size" empty="1">
		<attrs>
			<attr name="id" type="string" desc="Id."/>
			<attr name="size" type="string" desc="Base font size."/>
			<attr name="color" type="color" desc="Text color."/>
			<attr name="face" type="string" desc="Comma-separated list of font names."/>
		</attrs>
	</element>
	<!-- FONT TAG -->
	<element ename="FONT" edesc="Local change to font">
		<attrs>
&attrs;
<attr name="size" type="string" desc="Font size."/>
			<attr name="color" type="color" desc="Text color."/>
			<attr name="face" type="string" desc="Comma-separated list of font names."/>
		</attrs>
	</element>
	<!-- LIST TAGS -->
	<!-- FLOW TAGS -->
	<!-- BR TAG -->
	<element ename="BR" edesc="Forced line break" empty="1">
		<attrs>
&attrs;
<attr name="clear" type="enum" enum="left|all|right|none" desc="Control of text flow."/>
		</attrs>
	</element>
	<!-- NOBR TAG -->
	<element ename="NOBR" edesc="Define a non-breaking region" empty="1">
		<attrs>
</attrs>
	</element>
	<!-- PRE TAG -->
	<element ename="PRE" edesc="Define a region with no formatting">
		<attrs>
&attrs;
<attr name="width" type="number" desc="Width."/>
		</attrs>
	</element>
	<!-- HR TAG -->
	<element ename="HR" edesc="Horizontal line" empty="1">
		<attrs>
&attrs;
<attr name="align" type="enum" enum="left|right|center" desc="Alignment."/>
			<attr name="noshade" type="boolean" desc="No shading."/>
			<attr name="size" type="number" desc="Size."/>
			<attr name="width" type="number" desc="Override width."/>
		</attrs>
	</element>
	<!-- P TAG -->
	<element ename="P" edesc="Paragraph">
		<attrs>
&attrs;
<attr name="align" type="enum" enum="left|center|right|justify" desc="Alignment."/>
		</attrs>
	</element>
	<!-- H1 TAG -->
	<element ename="H1" edesc="Heading 1">
		<attrs>
&attrs;
<attr name="align" type="enum" enum="left|center|right|justify" desc="Alignment."/>
		</attrs>
	</element>
	<!-- H2 TAG -->
	<element ename="H2" edesc="Heading 2">
		<attrs>
&attrs;
<attr name="align" type="enum" enum="left|center|right|justify" desc="Alignment."/>
		</attrs>
	</element>
	<!-- H3 TAG -->
	<element ename="H3" edesc="Heading 3">
		<attrs>
&attrs;
<attr name="align" type="enum" enum="left|center|right|justify" desc="Alignment."/>
		</attrs>
	</element>
	<!-- H4 TAG -->
	<element ename="H4" edesc="Heading 4">
		<attrs>
&attrs;
<attr name="align" type="enum" enum="left|center|right|justify" desc="Alignment."/>
		</attrs>
	</element>
	<!-- H5 TAG -->
	<element ename="H5" edesc="Heading 5">
		<attrs>
&attrs;
<attr name="align" type="enum" enum="left|center|right|justify" desc="Alignment."/>
		</attrs>
	</element>
	<!-- H6 TAG -->
	<element ename="H6" edesc="Heading 6">
		<attrs>
&attrs;
<attr name="align" type="enum" enum="left|center|right|justify" desc="Alignment."/>
		</attrs>
	</element>
	<!-- Q TAG -->
	<element ename="Q" edesc="inline quotes">
		<attrs>
&attrs;
<attr name="cite" type="uri" desc="URI for source document or message."/>
		</attrs>
	</element>
	<!-- BLOCKQUOTE TAG -->
	<element ename="BLOCKQUOTE" edesc="long quotation">
		<attrs>
&attrs;
<attr name="cite" type="uri" desc="URI for source document or message."/>
		</attrs>
	</element>
	<!-- INS TAG -->
	<element ename="INS" edesc="inserted text">
		<attrs>
&attrs;
<attr name="cite" type="uri" desc="Reason for change."/>
			<attr name="datetime" type="datetime" desc="Date and time of the change."/>
		</attrs>
	</element>
	<!-- DEL TAG -->
	<element ename="DEL" edesc="deleted text">
		<attrs>
&attrs;
<attr name="cite" type="uri" desc="Reason for change."/>
			<attr name="datetime" type="datetime" desc="Date and time of the change."/>
		</attrs>
	</element>
	<!-- ANCHOR TAG -->
	<element ename="A" edesc="Anchor Tag">
		<attrs>
&attrs;

<attr name="charset" type="string" desc="Char encoding of linked resource."/>
			<attr name="type" type="string" desc="Advisory content type."/>
			<attr name="name" type="string" desc="Named link end."/>
			<attr name="href" type="uri" desc="URI for linked resource."/>
			<attr name="hreflang" type="string" desc="Language code."/>
			<attr name="target" type="string" desc="Render in this frame."/>
			<attr name="rel" type="string" desc="Forward link types."/>
			<attr name="rev" type="string" desc="Reverse link types."/>
			<attr name="accesskey" type="char" desc="Accessibility key character."/>
			<attr name="shape" type="string" desc="For use with client-side image maps."/>
			<attr name="coords" type="string" desc="For use with client-side image maps."/>
			<attr name="tabindex" type="number" desc="Position in tabbing order."/>
			<attr name="onfocus" cat="Event" type="script" desc="The element got the focus."/>
			<attr name="onblur" cat="Event" type="script" desc="The element lost the focus."/>
		</attrs>
	</element>
	<!-- UL TAG -->
	<element ename="UL" edesc="Unordered List Tag">
		<attrs>
&attrs;
</attrs>
	</element>
	<!-- OL TAG -->
	<element ename="OL" edesc="Ordered List Tag">
		<attrs>
&attrs;
<attr name="start" type="number" desc="Starting value for list."/>
			<attr name="type" type="enum" enumlist="A|a|I|i|1" desc="Numbering style for list."/>
		</attrs>
	</element>
	<!-- LI TAG -->
	<element ename="LI" edesc="List Item Tag">
		<attrs>
&attrs;
<attr name="type" type="enum" enumlist="A|a|I|i|1" desc="Numbering style for list item."/>
			<attr name="value" type="string" desc="Value for list item."/>
		</attrs>
	</element>
	<!-- STRUCTURE TAGS -->
	<!-- HTML TAG -->
	<element ename="HTML" edesc="Defines a complete HTML document.">
		<attrs>
&i18n;
</attrs>
	</element>
	<!-- HEAD TAG -->
	<element ename="HEAD" edesc="Defines an HTML document header.">
		<attrs>
&i18n;
</attrs>
	</element>
	<!-- META TAG -->
	<element ename="META" edesc="Supply additional information about a document." empty="1">
		<description>
Supplies information that a HTTP-server can use to generate extra HTTP headers, from the HTML data.
CSP supports http-equiv=content-type and http-equiv-expires.
</description>
		<attrs>
&i18n;

<attr name="http-equiv" type="enum" enum="content-type|expires|refresh|set-cookie" desc="Type of information supplied."/>
			<attr name="name" type="string" desc="Name of the meta data being defined."/>
			<attr name="content" type="string" desc="The value of the meta data for http-equiv or name."/>
			<attr name="scheme" type="string" desc="The format of the meta data for name."/>
		</attrs>
	</element>
	<!-- TITLE TAG -->
	<element ename="TITLE" edesc="Defines an HTML document title.">
		<attrs>
&i18n;
</attrs>
	</element>
	<!-- BODY TAG -->
	<element ename="BODY" edesc="Body Tag">
		<attrs>
&attrs;

<attr name="bgcolor" type="color" desc="Document background color."/>
			<attr name="text" type="color" desc="Document text color."/>
			<attr name="link" type="color" desc="Color of links."/>
			<attr name="vlink" type="color" desc="Color of visited links."/>
			<attr name="alink" type="color" desc="Color of selected links."/>
			<attr name="background" type="uri" desc="Texture tile for document background."/>
			<attr name="onload" cat="Event" type="script" desc="The document has been loaded."/>
			<attr name="onunload" cat="Event" type="script" desc="The document has been removed."/>
		</attrs>
	</element>
	<!-- ADDRESS TAG -->
	<element ename="ADDRESS" edesc="Author information">
		<attrs>
&attrs;
</attrs>
	</element>
	<!-- DIV TAG -->
	<element ename="DIV" edesc="DIV Tag">
		<attrs>
&attrs;
&csptext;
<attr name="align" type="enum" enum="&align;" desc="Text alignment."/>
		</attrs>
	</element>
	<!-- CENTER TAG -->
	<element ename="CENTER" edesc="Centered block">
		<attrs>
&attrs;
</attrs>
	</element>
	<!-- IMAGE MAPS -->
	<!-- MAP -->
	<element ename="MAP" edesc="Client-side image map">
		<attrs>
&attrs;
<attr name="name" type="string" desc="Name of map."/>
		</attrs>
	</element>
	<!-- AREA -->
	<element ename="AREA" edesc="Client-side image map area">
		<attrs>
&attrs;
<attr name="name" type="string" desc="name of map"/>
			<attr name="shape" type="string" desc="For use with client-side image maps."/>
			<attr name="coords" type="string" desc="For use with client-side image maps."/>
			<attr name="href" type="uri" desc="URI for linked resource."/>
			<attr name="target" type="string" desc="Render in this frame."/>
			<attr name="nohref" type="boolean" desc="This region has no action."/>
			<attr name="alt" type="string" desc="Short description."/>
			<attr name="tabindex" type="number" desc="Position in tabbing order."/>
			<attr name="accesskey" type="char" desc="Accessibility key character."/>
			<attr name="onfocus" cat="Event" type="script" desc="The element got the focus."/>
			<attr name="onblur" cat="Event" type="script" desc="The element lost the focus."/>
		</attrs>
	</element>
	<!-- THE LINK TAG -->
